package com.openbravo.pos.payment;


import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComponent;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author premsarojanand
 */
public class PaymentPanelPushtoPay extends javax.swing.JPanel implements PaymentPanel{
    
    private JPaymentNotifier m_notifier;
    private String m_sTransactionID;
    private double m_dTotal;
  

    /**
     * Creates new form PaymentPanelPushtoPay
     * 
     * @param notifier
     */
    public PaymentPanelPushtoPay(JPaymentNotifier notifier) {
        m_notifier = notifier;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        jButton1.setText("Intiate Transaction");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Confirm Payment");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(113, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(112, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        PaymentGatewayEzeeTab paymentGatewayEzeeTab = new PaymentGatewayEzeeTab();
        paymentGatewayEzeeTab.notify();
       
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    // End of variables declaration//GEN-END:variables

    @Override
    public void activate(String sTransaction, double dTotal) {
        m_sTransactionID = sTransaction;
        m_dTotal = dTotal;
        
         resetState();
//        jLabel1.setText(
//                m_dTotal > 0.0
//                //TODO: Needs to be done for all locals i.e. message.paymentgatewayemv
//                ? AppLocal.getIntString("message.paymentgatewayemv")
//                : AppLocal.getIntString("message.paymentgatewayemvrefund")); 
        m_notifier.setStatus(true, true);
    }
     private void resetState() {
        
        m_notifier.setStatus(false, false); 
        try {
            m_notifier.wait(10000);
        } catch (InterruptedException ex) {
            Logger.getLogger(PaymentPanelPushtoPay.class.getName()).log(Level.SEVERE, null, ex);
        }
     }

    @Override
    public JComponent getComponent() {
        return this;//To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public PaymentInfoMagcard getPaymentInfoMagcard() {
         if (m_dTotal > 0.0) {
            return new PaymentInfoMagcard(
                    "",
                    "", 
                    "",
                    null,
                    null,
                    null,
                    null,
                    null,
                    m_sTransactionID,
                    m_dTotal);
        } else {
            return new PaymentInfoMagcardRefund( 
                    "",
                    "", 
                    "",
                    null,
                    null,
                    null,
                    null, 
                    null,
                    m_sTransactionID,
                    m_dTotal);
        }
    }

    
}
